import { Capacitor } from '@capacitor/core';
import { notify } from './toast';

async function bytesToBase64(bytes) {
  let binary = '';
  const chunk = 0x8000;
  for (let i = 0; i < bytes.length; i += chunk) {
    binary += String.fromCharCode(...bytes.subarray(i, i + chunk));
  }
  return btoa(binary);
}

async function saveNative(data, filename, mimeType) {
  const [{ Filesystem, Directory }, { Share }] = await Promise.all([
    import('@capacitor/filesystem'),
    import('@capacitor/share'),
  ]);
  const bytes = data instanceof Uint8Array ? data : new Uint8Array(await data.arrayBuffer());
  const result = await Filesystem.writeFile({
    path: filename.replace(/[\\/:*?"<>|]/g, '_'),
    data: await bytesToBase64(bytes),
    directory: Directory.Documents,
    recursive: true,
  });

  notify(`Saved ${filename} to Documents.`, { type: 'success', title: 'File ready' });

  // The file is already persisted in Documents. Share is best-effort so the
  // user can immediately send/save it to another Android app (Drive, Files,
  // messaging, etc.) without making sharing a hard dependency for downloads.
  try {
    if ((await Share.canShare()).value) {
      await Share.share({
        title: filename,
        text: `MZ Smart Tool House: ${filename}`,
        files: [result.uri],
        dialogTitle: 'Save or share file',
      });
    }
  } catch {
    // Persisted download remains available even if the share sheet is closed.
  }
}

/** Saves generated bytes locally on Android or triggers a browser download on the web. */
export async function downloadBytes(bytes, filename, mimeType = 'application/octet-stream') {
  if (Capacitor.isNativePlatform()) return saveNative(bytes, filename, mimeType);
  const blob = new Blob([bytes], { type: mimeType });
  const url = URL.createObjectURL(blob);
  const link = document.createElement('a');
  link.href = url;
  link.download = filename;
  document.body.appendChild(link);
  link.click();
  document.body.removeChild(link);
  setTimeout(() => URL.revokeObjectURL(url), 1000);
  notify(`Prepared ${filename} for download.`, { type: 'success', title: 'Your file is ready' });
}

export async function downloadBlob(blob, filename) {
  if (Capacitor.isNativePlatform()) return saveNative(blob, filename, blob.type || 'application/octet-stream');
  const url = URL.createObjectURL(blob);
  const link = document.createElement('a');
  link.href = url;
  link.download = filename;
  document.body.appendChild(link);
  link.click();
  document.body.removeChild(link);
  setTimeout(() => URL.revokeObjectURL(url), 1000);
  notify(`Prepared ${filename} for download.`, { type: 'success', title: 'Your file is ready' });
}

/** Reads a File/Blob into a Uint8Array. */
export async function fileToUint8Array(file) {
  const buffer = await file.arrayBuffer();
  return new Uint8Array(buffer);
}
