import { Capacitor } from '@capacitor/core';
import { notify } from './toast';
import { assertNonEmptyOutput } from './files/outputValidation.js';

function safeFilename(filename = 'download') {
  const cleaned = String(filename || 'download').replace(/[\\/:*?"<>|\u0000-\u001f]/g, '_').trim();
  return cleaned || 'download';
}

async function bytesToBase64(bytes) {
  let binary = '';
  const chunk = 0x8000;
  for (let i = 0; i < bytes.length; i += chunk) {
    binary += String.fromCharCode(...bytes.subarray(i, i + chunk));
  }
  return btoa(binary);
}

async function saveNative(data, filename, mimeType) {
  assertNonEmptyOutput(data, 'Download');
  const [{ Filesystem, Directory }, { Share }] = await Promise.all([
    import('@capacitor/filesystem'),
    import('@capacitor/share'),
  ]);
  const bytes = data instanceof Uint8Array ? data : new Uint8Array(await data.arrayBuffer());
  const name = safeFilename(filename);
  const result = await Filesystem.writeFile({
    path: name,
    data: await bytesToBase64(bytes),
    directory: Directory.Documents,
    recursive: true,
  });

  notify(`Saved ${name} to Documents.`, { type: 'success', title: 'File ready' });

  try {
    if ((await Share.canShare()).value) {
      await Share.share({
        title: name,
        text: `MZ Smart Tool House: ${name}`,
        files: [result.uri],
        dialogTitle: 'Save or share file',
      });
    }
  } catch {
    // The persisted file remains available if sharing is cancelled/unavailable.
  }
}

function triggerBrowserDownload(blob, filename) {
  assertNonEmptyOutput(blob, 'Download');
  const url = URL.createObjectURL(blob);
  const link = document.createElement('a');
  link.href = url;
  link.download = safeFilename(filename);
  link.rel = 'noopener';
  document.body.appendChild(link);
  link.click();
  link.remove();
  // Keep the URL alive long enough for browsers that resolve downloads after
  // the click task, then always revoke it to avoid object-URL leaks.
  window.setTimeout(() => URL.revokeObjectURL(url), 1000);
}

/** Saves generated bytes locally on Android or triggers a browser download on the web. */
export async function downloadBytes(bytes, filename, mimeType = 'application/octet-stream') {
  assertNonEmptyOutput(bytes, 'Download');
  if (Capacitor.isNativePlatform()) return saveNative(bytes, filename, mimeType);
  const blob = new Blob([bytes], { type: mimeType });
  triggerBrowserDownload(blob, filename);
  notify(`Prepared ${safeFilename(filename)} for download.`, { type: 'success', title: 'Your file is ready' });
}

export async function downloadBlob(blob, filename) {
  assertNonEmptyOutput(blob, 'Download');
  if (Capacitor.isNativePlatform()) return saveNative(blob, filename, blob.type || 'application/octet-stream');
  triggerBrowserDownload(blob, filename);
  notify(`Prepared ${safeFilename(filename)} for download.`, { type: 'success', title: 'Your file is ready' });
}

/**
 * Downloads a validated OutputArtifact created by files/outputValidation.js.
 * This is the preferred API for new/migrated tools; legacy byte/blob helpers
 * remain for tools not yet migrated.
 */
export async function downloadArtifact(artifact) {
  if (!artifact?.data || !artifact?.filename) throw new Error('A valid output artifact is required.');
  assertNonEmptyOutput(artifact.data, 'Download');
  if (artifact.data instanceof Blob) return downloadBlob(artifact.data, artifact.filename);
  return downloadBytes(artifact.data, artifact.filename, artifact.mimeType);
}

/** Reads a File/Blob into a Uint8Array without modifying the original object. */
export async function fileToUint8Array(file) {
  if (!(file instanceof Blob)) throw new Error('A File or Blob is required.');
  const buffer = await file.arrayBuffer();
  return new Uint8Array(buffer);
}
