const u = (id, label, symbol, factor, extra = {}) => ({ id, label, symbol, factor, ...extra });
const linear = (config) => ({ kind: "linear", precision: 6, ...config });

export const converterRegistry = [
  linear({ id:"length", toolId:"length-converter", name:"Length & Distance Converter", category:"Everyday", description:"Convert metric, imperial, nautical and astronomical distance units with exact or defined standards.", baseUnit:"m", units:[
    u("m","Meter","m",1),u("km","Kilometer","km",1000),u("cm","Centimeter","cm",0.01),u("mm","Millimeter","mm",0.001),u("um","Micrometer","µm",1e-6),u("nm","Nanometer","nm",1e-9),u("mi","Mile","mi",1609.344),u("yd","Yard","yd",0.9144),u("ft","Foot","ft",0.3048),u("in","Inch","in",0.0254),u("nmi","Nautical Mile","nmi",1852),u("ly","Light Year","ly",9.4607304725808e15),u("au","Astronomical Unit","AU",149597870700)
  ], aliases:["distance","km miles","feet meters","inches cm"], keywords:["km to miles","miles to km","feet to meters","inch to cm"], relatedTools:["height","area","speed"] }),
  linear({ id:"mass", toolId:"weight-converter", name:"Weight & Mass Converter", category:"Everyday", description:"Convert metric and imperial mass units including kilograms, pounds, ounces, stones and tons.", baseUnit:"kg", units:[
    u("kg","Kilogram","kg",1),u("g","Gram","g",1e-3),u("mg","Milligram","mg",1e-6),u("ug","Microgram","µg",1e-9),u("t","Metric Ton / Tonne","t",1000),u("lb","Pound","lb",0.45359237),u("oz","Ounce","oz",0.028349523125),u("st","Stone","st",6.35029318),u("uston","US Ton (short)","US ton",907.18474),u("impton","Imperial Ton (long)","long ton",1016.0469088)
  ], aliases:["weight","kg lb","pounds kilograms"], keywords:["kg to lb","lb to kg","grams ounces"], relatedTools:["height","bmi","health-units"] }),
  { id:"height", toolId:"height-converter", name:"Height Converter", category:"Everyday", description:"Convert centimeters, meters, inches, decimal feet and feet + inches without confusing height with weight.", kind:"height", precision:4, aliases:["cm feet","feet inches","human height"], keywords:["cm to feet","feet inches to cm"], relatedTools:["mass","bmi","health-units"] },
  { id:"bmi", toolId:"bmi-unit-calculator", name:"BMI Calculator", category:"Health", description:"Calculate adult BMI from kg/lb and cm/meters/inches/feet + inches. Unit conversion and screening estimate only—not a diagnosis.", kind:"bmi", formula:"BMI = weight (kg) ÷ height (m)²", aliases:["body mass index","bmi kg lb","bmi feet inches"], keywords:["BMI calculator","kg cm BMI","lb ft BMI"], relatedTools:["height","mass","health-units"] },
  { id:"temperature", toolId:"temperature-converter", name:"Temperature Converter", category:"Everyday", description:"Convert Celsius, Fahrenheit, Kelvin and Rankine with thermodynamically correct formulas.", kind:"temperature", precision:4, units:[u("c","Celsius","°C",null),u("f","Fahrenheit","°F",null),u("k","Kelvin","K",null),u("r","Rankine","°R",null)], aliases:["c f","celsius fahrenheit"], keywords:["c to f","f to c","kelvin"], relatedTools:["cooking","health-units"] },
  linear({ id:"area", toolId:"area-converter", name:"Area Converter", category:"Everyday", description:"Convert square metric and imperial units, acres, hectares and square miles.", baseUnit:"m2", units:[u("m2","Square Meter","m²",1),u("km2","Square Kilometer","km²",1e6),u("cm2","Square Centimeter","cm²",1e-4),u("mm2","Square Millimeter","mm²",1e-6),u("in2","Square Inch","in²",0.00064516),u("ft2","Square Foot","ft²",0.09290304),u("yd2","Square Yard","yd²",0.83612736),u("acre","Acre","acre",4046.8564224),u("ha","Hectare","ha",10000),u("mi2","Square Mile","mi²",2589988.110336)], aliases:["square feet","acre hectare"], keywords:["sq ft to sq m","acre to hectare"], relatedTools:["land-area","length","volume"] }),
  linear({ id:"volume", toolId:"volume-converter", name:"Volume Converter", category:"Everyday", description:"Convert liters, cubic units and clearly labeled US/Imperial liquid measures.", baseUnit:"l", units:[u("l","Liter","L",1),u("ml","Milliliter","mL",0.001),u("m3","Cubic Meter","m³",1000),u("cm3","Cubic Centimeter","cm³",0.001),u("in3","Cubic Inch","in³",0.016387064),u("ft3","Cubic Foot","ft³",28.316846592),u("yd3","Cubic Yard","yd³",764.554857984),u("usgal","US Gallon","US gal",3.785411784),u("impgal","Imperial Gallon","Imp gal",4.54609),u("usqt","US Quart","US qt",0.946352946),u("uspt","US Pint","US pt",0.473176473),u("uscup","US Cup","US cup",0.2365882365),u("floz","US Fluid Ounce","fl oz",0.0295735295625),u("tbsp","US Tablespoon","tbsp",0.01478676478125),u("tsp","US Teaspoon","tsp",0.00492892159375)], aliases:["liters gallons","cup ml"], keywords:["liter to gallon","ml to oz","cup to ml"], relatedTools:["cooking","flow-rate"] }),
  linear({ id:"time", toolId:"time-unit-converter", name:"Time Unit Converter", category:"Time & Date", description:"Convert precise time units plus clearly labeled Gregorian-average month/year units. Use Date Converter for exact calendar arithmetic.", baseUnit:"s", units:[u("ns","Nanosecond","ns",1e-9),u("us","Microsecond","µs",1e-6),u("ms","Millisecond","ms",1e-3),u("s","Second","s",1),u("min","Minute","min",60),u("h","Hour","h",3600),u("d","Day","day",86400),u("week","Week","week",604800),u("month","Average Gregorian Month","month",2629746,{note:"365.2425 days ÷ 12"}),u("year","Average Gregorian Year","year",31556952,{note:"365.2425 days"}),u("decade","Average Decade","decade",315569520),u("century","Average Century","century",3155695200)], aliases:["duration units"], keywords:["seconds minutes","hours days"], note:"Month/year conversions are averages, not calendar date arithmetic.", relatedTools:["time-duration","date","timezone"] }),
  { id:"time-duration", toolId:"time-duration-converter", name:"Time Duration Converter", category:"Time & Date", description:"Combine days, hours, minutes and seconds and convert the duration into total hours, minutes or seconds.", kind:"duration", aliases:["hours minutes seconds"], keywords:["2 hours 35 minutes","duration converter"], relatedTools:["time","date"] },
  { id:"date", toolId:"date-converter", name:"Date Converter & Calculator", category:"Time & Date", description:"Find date differences, add/subtract calendar days, weeks, months or years, and count working days using unambiguous dates.", kind:"date", aliases:["date difference","add days","working days"], keywords:["days remaining","add months","subtract years"], relatedTools:["time","timezone"] },
  { id:"time-zone", toolId:"time-zone-converter", name:"Time Zone Converter", category:"Time & Date", description:"Convert a date and wall-clock time between real IANA time zones with daylight-saving and date changes handled by the browser timezone database.", kind:"timezone", aliases:["timezone","timezone conversion","lahore london dubai new york"], keywords:["time zone converter","DST","IANA timezone"], relatedTools:["time","date"] },
  linear({ id:"speed", toolId:"speed-converter", name:"Speed Converter", category:"Everyday", description:"Convert m/s, km/h, mph, ft/s, knots and an explicitly approximate Mach reference.", baseUnit:"ms", units:[u("ms","Meter/second","m/s",1),u("kmh","Kilometer/hour","km/h",1000/3600),u("mph","Mile/hour","mph",1609.344/3600),u("fts","Foot/second","ft/s",0.3048),u("knot","Knot","kn",1852/3600),u("mach","Mach (approx. at 20°C sea-level)","Mach",343,{note:"Speed of sound varies with temperature and medium."})], aliases:["kmh mph","knots"], keywords:["km/h to mph","m/s to km/h"], relatedTools:["acceleration","length"] }),
  linear({ id:"acceleration", toolId:"acceleration-converter", name:"Acceleration Converter", category:"Engineering", description:"Convert metric/imperial acceleration and standard gravity.", baseUnit:"ms2", units:[u("ms2","Meter/second²","m/s²",1),u("fts2","Foot/second²","ft/s²",0.3048),u("g0","Standard gravity","g₀",9.80665)], aliases:["g force"], keywords:["m/s2","ft/s2"], relatedTools:["speed","force"] }),
  linear({ id:"pressure", toolId:"pressure-converter", name:"Pressure Converter", category:"Engineering", description:"Convert Pa, kPa, MPa, bar, millibar, PSI, atmosphere, Torr, mmHg and inHg.", baseUnit:"pa", units:[u("pa","Pascal","Pa",1),u("kpa","Kilopascal","kPa",1000),u("mpa","Megapascal","MPa",1e6),u("bar","Bar","bar",1e5),u("mbar","Millibar","mbar",100),u("psi","PSI","psi",6894.757293168),u("atm","Atmosphere","atm",101325),u("torr","Torr","Torr",101325/760),u("mmhg","mmHg","mmHg",133.322387415),u("inhg","inHg (0°C)","inHg",3386.389)], aliases:["bar psi","atm kpa"], keywords:["psi to kpa","bar to psi"], relatedTools:["force","energy"] }),
  linear({ id:"energy", toolId:"energy-converter", name:"Energy Converter", category:"Engineering", description:"Convert joules, calories, watt-hours, electronvolts, BTU and foot-pounds using standard factors.", baseUnit:"j", units:[u("j","Joule","J",1),u("kj","Kilojoule","kJ",1e3),u("mj","Megajoule","MJ",1e6),u("cal","Thermochemical Calorie","cal",4.184),u("kcal","Kilocalorie","kcal",4184),u("wh","Watt-hour","Wh",3600),u("kwh","Kilowatt-hour","kWh",3.6e6),u("ev","Electronvolt","eV",1.602176634e-19),u("btu","BTU (IT)","BTU",1055.05585262),u("ftlb","Foot-pound","ft·lbf",1.3558179483314)], aliases:["joules calories","kwh"], keywords:["kwh to joules","kcal to kj"], relatedTools:["power","force"] }),
  linear({ id:"power", toolId:"power-converter", name:"Power Converter", category:"Engineering", description:"Convert watts, kilowatts, megawatts, mechanical horsepower and BTU/hour.", baseUnit:"w", units:[u("w","Watt","W",1),u("kw","Kilowatt","kW",1e3),u("mw","Megawatt","MW",1e6),u("hp","Mechanical Horsepower","hp",745.6998715822702),u("btuh","BTU/hour","BTU/h",0.2930710701722222)], aliases:["kw hp","horsepower"], keywords:["kw to hp","hp to kw"], relatedTools:["energy","electricity"] }),
  linear({ id:"data-storage", toolId:"data-unit-converter", name:"Data Storage Converter", category:"Digital & Developer", description:"Convert bits/bytes with decimal SI units and binary IEC units without mixing KB with KiB.", baseUnit:"byte", units:[u("bit","Bit","bit",1/8),u("byte","Byte","B",1),u("kbit","Kilobit (decimal)","kbit",1000/8),u("mbit","Megabit (decimal)","Mbit",1e6/8),u("gbit","Gigabit (decimal)","Gbit",1e9/8),u("tbit","Terabit (decimal)","Tbit",1e12/8),u("kb","Kilobyte (decimal)","KB",1e3),u("mb","Megabyte (decimal)","MB",1e6),u("gb","Gigabyte (decimal)","GB",1e9),u("tb","Terabyte (decimal)","TB",1e12),u("pb","Petabyte (decimal)","PB",1e15),u("kib","Kibibyte (binary)","KiB",1024),u("mib","Mebibyte (binary)","MiB",1024**2),u("gib","Gibibyte (binary)","GiB",1024**3),u("tib","Tebibyte (binary)","TiB",1024**4)], aliases:["mb gb","kb kib","file size"], keywords:["MB to GB","KiB bytes"], relatedTools:["data-speed","download-time"] }),
  linear({ id:"data-speed", toolId:"data-transfer-speed-converter", name:"Data Transfer Speed Converter", category:"Digital & Developer", description:"Convert bit/s and byte/s networking/storage speeds using decimal prefixes.", baseUnit:"bps", units:[u("bps","bit/second","bit/s",1),u("kbps","Kilobit/second","Kbit/s",1e3),u("mbps","Megabit/second","Mbit/s",1e6),u("gbps","Gigabit/second","Gbit/s",1e9),u("Bps","Byte/second","B/s",8),u("KBps","Kilobyte/second","KB/s",8e3),u("MBps","Megabyte/second","MB/s",8e6),u("GBps","Gigabyte/second","GB/s",8e9)], aliases:["internet speed","mbps mb/s"], keywords:["Mbps to MB/s","Gbps to MB/s"], relatedTools:["data-storage","download-time"] }),
  { id:"download-time", toolId:"download-time-calculator", name:"Download Time Calculator", category:"Digital & Developer", description:"Estimate transfer time from file size and connection speed using explicit byte/bit units.", kind:"download", aliases:["internet download time"], keywords:["GB Mbps download time"], relatedTools:["data-storage","data-speed"] },
  linear({ id:"frequency", toolId:"frequency-converter", name:"Frequency Converter", category:"Digital & Developer", description:"Convert Hertz through Terahertz for electronics, CPU, RAM and wireless frequencies.", baseUnit:"hz", units:[u("hz","Hertz","Hz",1),u("khz","Kilohertz","kHz",1e3),u("mhz","Megahertz","MHz",1e6),u("ghz","Gigahertz","GHz",1e9),u("thz","Terahertz","THz",1e12)], aliases:["mhz ghz"], keywords:["MHz to GHz","GHz to MHz"], relatedTools:["data-speed"] }),
  { id:"image-size", toolId:"image-size-converter", name:"Image Size & Aspect Ratio", category:"Digital & Developer", description:"Calculate aspect ratios and physical print size from pixels and DPI/PPI without pretending pixels have one universal physical size.", kind:"image-size", aliases:["aspect ratio","dpi ppi","pixels"], keywords:["1920 1080 16:9","pixels to inches"], relatedTools:["typography","data-storage"] },
  linear({ id:"angle", toolId:"angle-converter", name:"Angle Converter", category:"Science", description:"Convert degrees, radians, gradians, arcminutes, arcseconds and revolutions.", baseUnit:"rad", units:[u("rad","Radian","rad",1),u("deg","Degree","°",Math.PI/180),u("grad","Gradian","gon",Math.PI/200),u("arcmin","Arcminute","′",Math.PI/10800),u("arcsec","Arcsecond","″",Math.PI/648000),u("rev","Revolution","rev",Math.PI*2)], aliases:["degrees radians"], keywords:["degree to radian","radian to degree"], relatedTools:["length"] }),
  linear({ id:"force", toolId:"force-converter", name:"Force Converter", category:"Engineering", description:"Convert newtons, kilonewtons, dynes, pound-force and kilogram-force.", baseUnit:"n", units:[u("n","Newton","N",1),u("kn","Kilonewton","kN",1000),u("dyn","Dyne","dyn",1e-5),u("lbf","Pound-force","lbf",4.4482216152605),u("kgf","Kilogram-force","kgf",9.80665)], aliases:["newton lbf"], keywords:["N to lbf"], relatedTools:["torque","acceleration"] }),
  linear({ id:"torque", toolId:"torque-converter", name:"Torque Converter", category:"Engineering", description:"Convert N·m, lb·ft, lb·in and kgf·m torque units.", baseUnit:"nm", units:[u("nm","Newton-meter","N·m",1),u("lbft","Pound-foot","lb·ft",1.3558179483314),u("lbin","Pound-inch","lb·in",0.1129848290276167),u("kgfm","Kilogram-force meter","kgf·m",9.80665)], aliases:["nm lb ft"], keywords:["Nm to lb-ft"], relatedTools:["force","power"] }),
  linear({ id:"voltage", toolId:"voltage-converter", name:"Voltage Converter", category:"Engineering", description:"Convert millivolts, volts and kilovolts.", baseUnit:"v", units:[u("mv","Millivolt","mV",1e-3),u("v","Volt","V",1),u("kv","Kilovolt","kV",1e3)], aliases:["electric voltage"], keywords:["mV V kV"], relatedTools:["current","resistance","power"] }),
  linear({ id:"current", toolId:"current-converter", name:"Electric Current Converter", category:"Engineering", description:"Convert microamps, milliamps and amps.", baseUnit:"a", units:[u("ua","Microampere","µA",1e-6),u("ma","Milliampere","mA",1e-3),u("a","Ampere","A",1)], aliases:["amps milliamps"], keywords:["mA to A"], relatedTools:["voltage","resistance"] }),
  linear({ id:"resistance", toolId:"resistance-converter", name:"Resistance Converter", category:"Engineering", description:"Convert ohms, kiloohms and megaohms.", baseUnit:"ohm", units:[u("ohm","Ohm","Ω",1),u("kohm","Kiloohm","kΩ",1e3),u("mohm","Megaohm","MΩ",1e6)], aliases:["ohms"], keywords:["kiloohm megaohm"], relatedTools:["voltage","current"] }),
  linear({ id:"charge", toolId:"electric-charge-converter", name:"Electric Charge Converter", category:"Engineering", description:"Convert coulombs, ampere-hours and milliampere-hours.", baseUnit:"c", units:[u("c","Coulomb","C",1),u("ah","Ampere-hour","Ah",3600),u("mah","Milliampere-hour","mAh",3.6)], aliases:["mah ah coulomb"], keywords:["mAh to Ah"], relatedTools:["current","energy"] }),
  linear({ id:"illuminance", toolId:"illuminance-converter", name:"Illuminance Converter", category:"Science", description:"Convert lux and foot-candles. Lumens are luminous flux and require area, so they are not falsely treated as directly convertible.", baseUnit:"lux", units:[u("lux","Lux","lx",1),u("fc","Foot-candle","fc",10.763910416709722)], aliases:["lux foot candle"], keywords:["lux to foot candle"], note:"Lumens cannot be converted directly to lux without an illuminated area.", relatedTools:["area"] }),
  { id:"fuel-economy", toolId:"fuel-economy-converter", name:"Fuel Economy Converter", category:"Everyday", description:"Convert km/L, L/100 km, US MPG and Imperial MPG using reciprocal formulas.", kind:"fuel", aliases:["mpg l/100km"], keywords:["mpg to l/100km","km/l"], relatedTools:["volume","length"] },
  { id:"cooking", toolId:"cooking-converter", name:"Cooking Converter", category:"Everyday", description:"Convert common cooking volumes and oven temperatures. Weight conversions require ingredient density and are not guessed.", kind:"cooking", aliases:["cups ml","oven c f"], keywords:["teaspoon tablespoon cup","oven temperature"], relatedTools:["volume","temperature"] },
  { id:"health-units", toolId:"health-unit-converter", name:"Health Units Converter", category:"Health", description:"Convert common measurement units including glucose and cholesterol with analyte-specific factors. Unit conversion only—not medical advice.", kind:"health", aliases:["glucose mmol mgdl","cholesterol"], keywords:["mg/dL mmol/L"], relatedTools:["height","mass","temperature"] },
  { id:"currency", toolId:"currency-converter", name:"Currency Converter", category:"Finance", description:"Convert major currencies using live exchange-rate data when available, with last-updated/source information and manual-rate fallback.", kind:"currency", aliases:["pkr usd","exchange rate"], keywords:["USD PKR","AED PKR","currency rates"], requiresInternet:true, relatedTools:["crypto"] },
  { id:"crypto", toolId:"crypto-converter", name:"Cryptocurrency Converter", category:"Finance", description:"Convert supported cryptocurrencies using live market data with timestamp/source. Static values are never presented as live.", kind:"crypto", aliases:["btc eth usdt"], keywords:["bitcoin usd","ethereum"], requiresInternet:true, relatedTools:["currency"] },
  { id:"number-system", toolId:"number-system-converter", name:"Number System Converter", category:"Student & Developer", description:"Convert binary, decimal, octal and hexadecimal values, plus ASCII code representations.", kind:"number-system", aliases:["binary decimal hex octal ascii"], keywords:["decimal to binary","hex to decimal"], relatedTools:["roman","fraction"] },
  { id:"roman", toolId:"roman-numeral-converter", name:"Roman Numeral Converter", category:"Student & Developer", description:"Convert integers to canonical Roman numerals and validate Roman numeral input before converting back.", kind:"roman", aliases:["roman number"], keywords:["number to roman","roman to number"], relatedTools:["number-system"] },
  { id:"percentage", toolId:"percentage-converter", name:"Percentage Converter", category:"Student & Developer", description:"Convert decimal, percentage and fractions, and calculate percentage increase/decrease.", kind:"percentage", aliases:["decimal percent fraction"], keywords:["percentage to decimal","fraction to percentage"], relatedTools:["fraction"] },
  { id:"fraction", toolId:"fraction-converter", name:"Fraction Converter", category:"Student & Developer", description:"Convert decimals to simplified fractions and fractions/mixed numbers to decimals or improper fractions.", kind:"fraction", aliases:["decimal fraction","mixed number"], keywords:["decimal to fraction","improper fraction"], relatedTools:["percentage"] },
  linear({ id:"density", toolId:"density-converter", name:"Density Converter", category:"Science", description:"Convert common mass-density units.", baseUnit:"kgm3", units:[u("kgm3","Kilogram/cubic meter","kg/m³",1),u("gcm3","Gram/cubic centimeter","g/cm³",1000),u("gml","Gram/milliliter","g/mL",1000),u("lbft3","Pound/cubic foot","lb/ft³",16.01846337396),u("lbin3","Pound/cubic inch","lb/in³",27679.904710191)], aliases:["kg m3 g cm3"], keywords:["density units"], relatedTools:["volume","mass"] }),
  linear({ id:"molar-mass", toolId:"molar-mass-converter", name:"Molar Mass Converter", category:"Science", description:"Convert g/mol and kg/kmol (numerically equivalent units).", baseUnit:"gmol", units:[u("gmol","Gram/mole","g/mol",1),u("kgkmol","Kilogram/kilomole","kg/kmol",1)], aliases:["g/mol kg/kmol"], keywords:["molar mass units"], relatedTools:["concentration"] }),
  { id:"concentration", toolId:"concentration-converter", name:"Concentration Converter", category:"Science", description:"Convert mass or molar concentration. Cross-conversion asks for molar mass instead of guessing a substance density/molar mass.", kind:"concentration", aliases:["mol l mmol l mg l"], keywords:["mol/L mmol/L","mg/L g/L"], relatedTools:["molar-mass","density"] },
  { id:"radiation", toolId:"radiation-units-converter", name:"Radiation Units Converter", category:"Science", description:"Convert within absorbed dose, equivalent dose, or activity dimensions without incorrectly mixing Gray, Sievert and Becquerel.", kind:"radiation", aliases:["gray sievert becquerel"], keywords:["Gy Sv Bq"], relatedTools:["energy"] },
  linear({ id:"flow-rate", toolId:"flow-rate-converter", name:"Flow Rate Converter", category:"Engineering", description:"Convert L/s, L/min, L/h, cubic meters per time and US gallons per minute.", baseUnit:"ls", units:[u("ls","Liter/second","L/s",1),u("lmin","Liter/minute","L/min",1/60),u("lh","Liter/hour","L/h",1/3600),u("m3s","Cubic meter/second","m³/s",1000),u("m3min","Cubic meter/minute","m³/min",1000/60),u("m3h","Cubic meter/hour","m³/h",1000/3600),u("gpm","US gallon/minute","US gpm",3.785411784/60)], aliases:["gpm l min"], keywords:["L/min to gpm"], relatedTools:["volume","pressure"] }),
  { id:"typography", toolId:"typography-converter", name:"Typography & CSS Unit Converter", category:"Digital & Developer", description:"Convert px, rem, em, pt and physical dimensions with explicit root/font size and DPI assumptions.", kind:"typography", aliases:["px rem em pt dpi"], keywords:["px to rem","pt to px","cm to px"], relatedTools:["image-size"] },
  { id:"land-area", toolId:"land-area-converter", name:"Pakistan Land Area Converter", category:"Pakistan", description:"Convert square feet/yards/meters, acre, hectare, Marla and Kanal with a selectable Pakistan Marla standard.", kind:"land", aliases:["marla kanal","pakistan land"], keywords:["marla to square feet","kanal acre"], relatedTools:["area"] },
].map((c)=>({
  precision: c.precision ?? 6,
  processingType: c.requiresInternet ? "api" : "browser",
  requiresBackend: Boolean(c.requiresBackend),
  requiresInternet: Boolean(c.requiresInternet),
  formula: c.formula || (c.kind === "linear" ? "result = value × fromFactor ÷ toFactor" : "Specialized validated conversion formula"),
  seoTitle: c.seoTitle || `${c.name} – Free Online Converter | MZ Smart Tool House`,
  seoDescription: c.seoDescription || c.description,
  ...c,
}));

export const converterCategories = ["Popular","Everyday","Time & Date","Student & Developer","Digital & Developer","Engineering","Science","Health","Finance","Pakistan"];

export const converterToolRecords = [
  { id:"universal-conversion-hub", name:"Universal Conversion Hub", category:"converter-tools", route:"/convert", description:"One professional hub for everyday, student, developer, science, engineering, health and finance conversions.", icon:"refresh-cw", keywords:["convert","converter","units","universal converter"], aliases:["all converters"], status:"active", popular:true, isNew:true, processingType:"browser" },
  ...converterRegistry.map((c)=>({
    id:c.toolId,
    slug:c.id,
    route:`/convert/${c.id}`,
    name:c.name,
    category:"converter-tools",
    description:c.description,
    icon:c.kind==="currency"?"badge-dollar-sign":"refresh-cw",
    keywords:[...(c.keywords||[]),...(c.aliases||[]),"converter"],
    aliases:c.aliases||[],
    status:"active",
    processingType:c.requiresInternet?"api":"browser",
    requiresInternet:Boolean(c.requiresInternet),
    seoTitle:`${c.name} – Free Online Conversion Tool | MZ Smart Tool House`,
    seoDescription:c.description,
    relatedTools:(c.relatedTools||[]).map((id)=>converterRegistry.find((x)=>x.id===id)?.toolId).filter(Boolean),
  })),
];

export function getConverter(id){ return converterRegistry.find((c)=>c.id===id || c.toolId===id); }
export function getConverterByToolId(id){ return converterRegistry.find((c)=>c.toolId===id); }
