import { useMemo, useState } from "react";
import { Link } from "react-router-dom";
import { ArrowRight, Heart, Search, Sparkles } from "lucide-react";
import Seo, { BASE_URL } from "../../components/layout/Seo";
import { converterCategories, converterRegistry } from "./conversionRegistry";
import { clearConversionHistory, getConversionHistory, getConverterFavorites } from "./converterPreferences";

const popular=["mass","height","temperature","length","data-storage","data-speed","currency","volume"];
export default function ConversionHub(){
 const [query,setQuery]=useState(""); const [category,setCategory]=useState("Popular"); const [history,setHistory]=useState(()=>getConversionHistory()); const favorites=getConverterFavorites();
 const filtered=useMemo(()=>{const q=query.trim().toLowerCase();let list=converterRegistry.filter(c=>!q||[c.name,c.description,c.id,...(c.aliases||[]),...(c.keywords||[])].join(" ").toLowerCase().includes(q));if(!q&&category==="Popular")list=list.filter(c=>popular.includes(c.id));else if(!q&&category!=="Popular")list=list.filter(c=>c.category===category);return list},[query,category]);
 const schema={"@context":"https://schema.org","@type":"CollectionPage",name:"Universal Conversion Hub",url:`${BASE_URL}/convert`,description:"Professional unit, science, engineering, developer, health, finance and Pakistan-focused conversion tools.",mainEntity:{"@type":"ItemList",numberOfItems:converterRegistry.length,itemListElement:converterRegistry.map((c,i)=>({"@type":"ListItem",position:i+1,name:c.name,url:`${BASE_URL}/convert/${c.id}`}))}};
 return <div className="mz-section py-8 sm:py-12"><Seo path="/convert" title="Universal Converter – Units, Science, Data, Currency & More" description="Convert length, weight, height, temperature, area, volume, time, speed, pressure, energy, data, engineering units, health units, currencies and more with tested formulas." schema={schema}/>
  <section className="overflow-hidden rounded-3xl border border-cyan-100 bg-gradient-to-br from-cyan-50 via-white to-blue-50 p-6 shadow-soft dark:border-cyan-950/60 dark:from-cyan-950/25 dark:via-navy-900 dark:to-blue-950/20 sm:p-9"><div className="grid gap-8 lg:grid-cols-[1fr_.65fr]"><div><span className="mz-eyebrow">Conversion Hub</span><h1 className="mt-3 text-4xl font-black tracking-tight sm:text-5xl">Universal Converter</h1><p className="mt-4 max-w-3xl text-base leading-7 text-navy-600 dark:text-navy-300">One place for everyday, student, developer, science, engineering, health, finance and Pakistan-focused conversions. Static unit conversions stay in your browser; live-rate tools clearly show when internet data is required.</p><div className="relative mt-6 max-w-2xl"><Search className="pointer-events-none absolute left-4 top-1/2 h-5 w-5 -translate-y-1/2 text-navy-400"/><input className="mz-input py-4 pl-12 text-base" value={query} onChange={e=>setQuery(e.target.value)} placeholder="Search: kg to lb, cm to feet, Mbps, pressure, currency…"/></div></div><div className="rounded-3xl border border-white/80 bg-white/80 p-5 shadow-sm dark:border-navy-700 dark:bg-navy-900/80"><Sparkles className="h-7 w-7 text-cyan-600"/><strong className="mt-3 block text-lg">Designed for real use</strong><p className="mt-2 text-sm leading-6 text-navy-500">No fake live rates, no mixing KB with KiB, no pretending lumens equal lux, and no hard-coded DST offsets.</p></div></div></section>
  {!query&&<div className="mt-7 flex gap-2 overflow-x-auto pb-2 lg:hidden">{converterCategories.map(c=><button key={c} className={category===c?"mz-btn-primary whitespace-nowrap":"mz-btn-secondary whitespace-nowrap"} onClick={()=>setCategory(c)}>{c}</button>)}</div>}
  <div className="mt-8 lg:grid lg:grid-cols-[220px_minmax(0,1fr)] lg:gap-7">
   <aside className="hidden lg:block"><div className="mz-card sticky top-24 p-3"><div className="px-2 pb-2 text-xs font-bold uppercase tracking-wider text-navy-400">Categories</div>{converterCategories.map(c=><button key={c} className={`mb-1 w-full rounded-xl px-3 py-2.5 text-left text-sm font-semibold transition ${category===c?"bg-brand-600 text-white":"hover:bg-navy-50 dark:hover:bg-navy-800"}`} onClick={()=>{setCategory(c);setQuery("")}}>{c}</button>)}</div></aside>
   <main className="min-w-0">
    {history.length>0&&!query&&<section><div className="mb-3 flex items-center justify-between gap-3"><div><h2 className="text-xl font-bold">Recent conversions</h2><p className="mt-1 text-sm text-navy-500">Stored only in this browser.</p></div><button className="mz-btn-ghost" type="button" onClick={()=>setHistory(clearConversionHistory())}>Clear history</button></div><div className="grid gap-3 sm:grid-cols-2 xl:grid-cols-4">{history.slice(0,8).map(h=><Link key={h.id} to={`/convert/${h.converterId}`} className="mz-card mz-card-hover p-4"><strong className="block truncate">{h.converterName}</strong><span className="mt-1 block truncate text-sm text-navy-500">{h.input} {h.from} → {h.result}</span></Link>)}</div></section>}
    {favorites.length>0&&!query&&<section className="mt-8"><div className="mb-3 flex items-center gap-2"><Heart className="h-5 w-5 fill-rose-500 text-rose-500"/><h2 className="text-xl font-bold">Favorites</h2></div><div className="grid gap-3 sm:grid-cols-2 xl:grid-cols-4">{converterRegistry.filter(c=>favorites.includes(c.id)).map(c=><ConverterCard key={c.id} c={c}/>)}</div></section>}
    <section className={history.length||favorites.length?"mt-8":""}><div className="mb-4 flex items-end justify-between gap-3"><div><h2 className="text-2xl font-black">{query?`Results for “${query}”`:category}</h2><p className="mt-1 text-sm text-navy-500">{filtered.length} converter{filtered.length===1?"":"s"}</p></div></div>{filtered.length?<div className="grid gap-4 sm:grid-cols-2 xl:grid-cols-3">{filtered.map(c=><ConverterCard key={c.id} c={c}/>)}</div>:<div className="mz-card p-8 text-center text-navy-500">No matching converters. Try “temperature”, “data”, “Pakistan land”, or “currency”.</div>}</section>
   </main>
  </div>
  <section className="mt-12 grid gap-4 lg:grid-cols-3"><Info title="Everyday">Height, weight, temperature, length, area, volume, cooking and fuel economy.</Info><Info title="Student & Developer">Number systems, fractions, percentages, storage, transfer speed, typography and image dimensions.</Info><Info title="Engineering & Science">Pressure, energy, power, force, torque, flow rate, density, concentration and radiation dimensions.</Info></section>
 </div>
}
function ConverterCard({c}){return <Link to={`/convert/${c.id}`} className="mz-card mz-card-hover group p-5"><div className="text-xs font-bold uppercase tracking-wide text-cyan-600">{c.category}</div><h3 className="mt-2 text-lg font-extrabold">{c.name}</h3><p className="mt-2 line-clamp-3 text-sm leading-6 text-navy-500 dark:text-navy-400">{c.description}</p><span className="mt-4 inline-flex items-center gap-1 text-sm font-bold text-brand-600">Open converter <ArrowRight className="h-4 w-4 transition group-hover:translate-x-1"/></span></Link>}
function Info({title,children}){return <div className="mz-card p-5"><h3 className="font-bold">{title}</h3><p className="mt-2 text-sm leading-6 text-navy-500">{children}</p></div>}
