import { Link, useParams } from "react-router-dom";
import Seo, { BASE_URL } from "../components/layout/Seo";
import Breadcrumbs from "../components/layout/Breadcrumbs";
import ConversionTool from "../tools/converters/ConversionTool";
import { converterRegistry, getConverter } from "../tools/converters/conversionRegistry";
import TimeZoneConverter from "../tools/reference/TimeZoneConverter";
import NotFound from "./NotFound";

export default function ConversionPage(){const {converterSlug}=useParams();const spec=getConverter(converterSlug);if(!spec)return <NotFound/>;const related=(spec.relatedTools||[]).map(getConverter).filter(Boolean);const schema={"@context":"https://schema.org","@graph":[{"@type":"WebApplication",name:spec.name,description:spec.description,url:`${BASE_URL}/convert/${spec.id}`,applicationCategory:"UtilitiesApplication",operatingSystem:"Any",offers:{"@type":"Offer",price:"0",priceCurrency:"USD"}},{"@type":"BreadcrumbList",itemListElement:[{"@type":"ListItem",position:1,name:"Home",item:`${BASE_URL}/`},{"@type":"ListItem",position:2,name:"Universal Converter",item:`${BASE_URL}/convert`},{"@type":"ListItem",position:3,name:spec.name,item:`${BASE_URL}/convert/${spec.id}`}]}]};return <div className="mz-section py-7 sm:py-10"><Seo path={`/convert/${spec.id}`} title={`${spec.name} – Free Online Converter`} description={spec.description} schema={schema}/><Breadcrumbs items={[{label:"Universal Converter",href:"/convert"},{label:spec.name}]}/><section className="mt-5"><div className="mb-6"><span className="mz-eyebrow">{spec.category}</span><h1 className="mt-2 text-3xl font-black tracking-tight sm:text-4xl">{spec.name}</h1><p className="mt-3 max-w-3xl text-sm leading-6 text-navy-500 dark:text-navy-400">{spec.description}</p></div>{spec.kind==="timezone"?<TimeZoneConverter/>:<ConversionTool converterId={spec.id}/>}</section>{related.length>0&&<section className="mt-10"><h2 className="text-xl font-bold">Related converters</h2><div className="mt-4 grid gap-3 sm:grid-cols-2 lg:grid-cols-4">{related.map(c=><Link key={c.id} to={`/convert/${c.id}`} className="mz-card mz-card-hover p-4"><strong>{c.name}</strong><span className="mt-1 block text-xs text-navy-500">{c.description}</span></Link>)}</div></section>}<section className="mt-10 rounded-3xl bg-navy-50 p-6 dark:bg-navy-900"><h2 className="text-xl font-bold">How to use</h2><ol className="mt-3 list-decimal space-y-2 pl-5 text-sm leading-6 text-navy-600 dark:text-navy-300"><li>Enter the value or information you want to convert.</li><li>Select the source and target units or conversion mode.</li><li>Review the live result; swap units where supported.</li><li>Copy the result or reuse a recent conversion. History stays in your browser.</li></ol></section></div>}
