import { useEffect, useMemo, useState } from "react";
import { ArrowRight, Clock3, FileText, Globe2, Presentation, ScanLine, Table2, TerminalSquare } from "lucide-react";
import { Link } from "react-router-dom";
import { getToolById } from "../../data/tools";

const ACTIONS=[
 ["Write Assignment","mz-online-word",FileText,"bg-blue-50 text-blue-700 dark:bg-blue-950/40 dark:text-blue-300"],
 ["Create Spreadsheet","mz-online-excel",Table2,"bg-emerald-50 text-emerald-700 dark:bg-emerald-950/40 dark:text-emerald-300"],
 ["Create Presentation","mz-online-powerpoint",Presentation,"bg-orange-50 text-orange-700 dark:bg-orange-950/40 dark:text-orange-300"],
 ["Scan Document","smart-document-scanner",ScanLine,"bg-teal-50 text-teal-700 dark:bg-teal-950/40 dark:text-teal-300"],
 ["Programming Lab","programming-lab",TerminalSquare,"bg-indigo-50 text-indigo-700 dark:bg-indigo-950/40 dark:text-indigo-300"],
 ["World Clock","world-clock",Globe2,"bg-cyan-50 text-cyan-700 dark:bg-cyan-950/40 dark:text-cyan-300"],
];
function greeting(){const h=new Date().getHours();return h<12?"Good morning":h<18?"Good afternoon":"Good evening";}
export default function DashboardQuickStart(){const[now,setNow]=useState(()=>new Date());useEffect(()=>{const timer=setInterval(()=>setNow(new Date()),60000);return()=>clearInterval(timer)},[]);const times=useMemo(()=>[["Lahore","Asia/Karachi"],["London","Europe/London"],["New York","America/New_York"]].map(([city,zone])=>({city,time:new Intl.DateTimeFormat(undefined,{hour:"2-digit",minute:"2-digit",timeZone:zone}).format(now)})),[now]);return <section className="mz-section py-8 sm:py-10"><div className="overflow-hidden rounded-3xl border border-navy-100 bg-gradient-to-br from-white via-brand-50/40 to-cyan-50/50 p-5 shadow-soft dark:border-navy-800 dark:from-navy-900 dark:via-brand-950/10 dark:to-cyan-950/10 sm:p-7"><div className="flex flex-wrap items-end justify-between gap-3"><div><span className="mz-eyebrow">YOUR PRODUCTIVITY DASHBOARD</span><h2 className="mt-2 text-2xl font-black tracking-tight sm:text-3xl">{greeting()}. Ready to get something done?</h2><p className="mt-2 text-sm leading-6 text-navy-500 dark:text-navy-400">Jump straight into common work. Your recent and favorite tools stay on this device.</p></div><Link to="/tools" className="mz-btn-ghost">All tools <ArrowRight className="h-4 w-4"/></Link></div><div className="mt-6 grid gap-3 sm:grid-cols-2 lg:grid-cols-3 xl:grid-cols-6">{ACTIONS.map(([label,id,Icon,tone])=>{const tool=getToolById(id);return tool?<Link key={id} to={tool.route} className="group rounded-2xl border border-white/80 bg-white/85 p-4 shadow-sm transition hover:-translate-y-0.5 hover:shadow-md dark:border-navy-800 dark:bg-navy-900/85"><span className={`flex h-10 w-10 items-center justify-center rounded-xl ${tone}`}><Icon className="h-5 w-5"/></span><strong className="mt-3 block text-sm">{label}</strong><span className="mt-1 block text-xs text-navy-400">Open workspace</span></Link>:null})}</div><div className="mt-5 flex flex-wrap items-center gap-2 rounded-2xl border border-navy-100/70 bg-white/65 p-3 dark:border-navy-800 dark:bg-navy-950/40"><span className="mr-1 inline-flex items-center gap-2 text-xs font-bold uppercase tracking-wide text-navy-400"><Clock3 className="h-4 w-4"/> World time</span>{times.map((item)=><span key={item.city} className="rounded-xl bg-white px-3 py-2 text-xs shadow-sm dark:bg-navy-900"><b>{item.city}</b> · <span className="tabular-nums">{item.time}</span></span>)}<Link to={getToolById("world-clock")?.route||"/tools/world-clock"} className="ml-auto text-xs font-bold text-brand-600">Manage cities →</Link></div></div></section>}
