import { useEffect, useMemo, useRef, useState } from "react";
import { Copy, Download, Image as ImageIcon, MonitorPlay, Plus, Save, Trash2, Upload } from "lucide-react";
import { downloadBytes } from "../../lib/download";

const STORAGE_KEY="mz-online-powerpoint-deck-v1";
const uid=()=>globalThis.crypto?.randomUUID?.()||`${Date.now()}-${Math.random()}`;
function blankSlide(layout="title-content"){return{id:uid(),layout,title:layout==="title"?"Presentation Title":"Slide Title",body:layout==="title"?"Subtitle":"Add your key points here",notes:"",background:"#ffffff",image:""};}
function readDeck(){try{const d=JSON.parse(localStorage.getItem(STORAGE_KEY)||"null");if(d?.slides?.length)return d}catch{}return{title:"Untitled Presentation",slides:[blankSlide("title")],active:0};}
function escapeXml(value){return String(value??"").replace(/[&<>]/g,(c)=>({"&":"&amp;","<":"&lt;",">":"&gt;"}[c]));}

async function imageDimensions(dataUrl){return new Promise((resolve,reject)=>{const img=new Image();img.onload=()=>resolve({width:img.naturalWidth,height:img.naturalHeight});img.onerror=()=>reject(new Error("Image could not be read."));img.src=dataUrl;});}

function SlideCanvas({slide,compact=false}){
 return <div className={`relative aspect-video overflow-hidden bg-white shadow ${compact?"rounded-lg":"rounded-2xl"}`} style={{backgroundColor:slide.background}}>
  <div className={`${compact?"p-3":"p-8 sm:p-12"} flex h-full flex-col`}>
   <h3 className={`${compact?"text-[9px]":"text-2xl sm:text-4xl"} font-black leading-tight text-slate-900`}>{slide.title||"Untitled slide"}</h3>
   {slide.layout!=="title"?<div className={`${compact?"mt-2 text-[6px]":"mt-5 whitespace-pre-wrap text-base sm:text-xl"} leading-relaxed text-slate-700`}>{slide.body}</div>:<p className={`${compact?"mt-2 text-[7px]":"mt-5 text-lg sm:text-2xl"} text-slate-500`}>{slide.body}</p>}
   {slide.image?<img src={slide.image} alt="Slide visual" className={`${slide.layout==="image"?"mt-3 h-[62%] w-full object-contain":"absolute bottom-5 right-5 h-[36%] max-w-[42%] object-contain"}`}/>:null}
  </div>
 </div>;
}

export default function OnlinePowerPoint(){
 const initial=useMemo(readDeck,[]);const[title,setTitle]=useState(initial.title||"Untitled Presentation");const[slides,setSlides]=useState(initial.slides);const[active,setActive]=useState(Math.min(initial.active||0,initial.slides.length-1));const[saveState,setSaveState]=useState("Saved");const[error,setError]=useState("");const[message,setMessage]=useState("");const[presenting,setPresenting]=useState(false);const imageRef=useRef(null);const slide=slides[active];
 useEffect(()=>{setSaveState("Saving…");const t=setTimeout(()=>{try{localStorage.setItem(STORAGE_KEY,JSON.stringify({title,slides,active,savedAt:Date.now()}));setSaveState("Saved")}catch{setSaveState("Local save unavailable")}},450);return()=>clearTimeout(t)},[title,slides,active]);
 const update=(patch)=>setSlides((all)=>all.map((item,index)=>index===active?{...item,...patch}:item));
 const add=(layout="title-content")=>{const next=blankSlide(layout);setSlides((all)=>[...all,next]);setActive(slides.length)};
 const duplicate=()=>{const next={...slide,id:uid()};setSlides((all)=>[...all.slice(0,active+1),next,...all.slice(active+1)]);setActive(active+1)};
 const remove=()=>{if(slides.length===1){setError("A presentation must contain at least one slide.");return;}setSlides((all)=>all.filter((_,i)=>i!==active));setActive(Math.max(0,active-1))};
 const move=(delta)=>{const target=active+delta;if(target<0||target>=slides.length)return;setSlides((all)=>{const next=[...all];[next[active],next[target]]=[next[target],next[active]];return next});setActive(target)};
 function imageFile(file){if(!file)return;if(!/^image\/(png|jpeg|webp)$/.test(file.type)){setError("Choose a PNG, JPG or WebP image.");return;}if(file.size>8*1024*1024){setError("Choose an image under 8 MB.");return;}const reader=new FileReader();reader.onload=()=>update({image:String(reader.result)});reader.onerror=()=>setError("Image could not be read.");reader.readAsDataURL(file);}
 function template(kind){const presets={university:[{...blankSlide("title"),title:"University Presentation",body:"Course • Student • Date"},{...blankSlide(),title:"Introduction",body:"• Context\n• Objective\n• Scope"},{...blankSlide(),title:"Main Findings",body:"• Key point one\n• Key point two\n• Supporting evidence"},{...blankSlide(),title:"Conclusion",body:"Summary and next steps"}],research:[{...blankSlide("title"),title:"Research Presentation",body:"Researcher • Institution"},{...blankSlide(),title:"Research Question",body:"Problem, gap and objective"},{...blankSlide(),title:"Methodology",body:"Design • Sample • Data collection"},{...blankSlide(),title:"Results",body:"Key findings and evidence"},{...blankSlide(),title:"Conclusion",body:"Implications • Limitations • Future work"}],business:[{...blankSlide("title"),title:"Business Presentation",body:"Company • Presenter"},{...blankSlide(),title:"Opportunity",body:"Customer problem and market"},{...blankSlide(),title:"Solution",body:"Product and value proposition"},{...blankSlide(),title:"Plan",body:"Execution, milestones and metrics"}]};const next=presets[kind]||[{...blankSlide("title"),title:"Project Presentation",body:"Project • Team • Date"},{...blankSlide(),title:"Overview",body:"Objective and scope"},{...blankSlide(),title:"Progress",body:"Milestones and current status"},{...blankSlide(),title:"Next Steps",body:"Actions and timeline"}];setSlides(next);setActive(0);setTitle(next[0].title);setMessage("Presentation template applied. Every slide remains editable.");}
 async function exportPptx(){setError("");try{const PptxGenJS=(await import("pptxgenjs")).default;const pptx=new PptxGenJS();pptx.layout="LAYOUT_WIDE";pptx.author="MZ Smart Tool House";pptx.subject=title;pptx.title=title;for(const item of slides){const s=pptx.addSlide();s.background={color:item.background.replace("#","")};s.addText(item.title||"",{x:.65,y:.45,w:12,h:.75,fontFace:"Aptos Display",fontSize:item.layout==="title"?30:26,bold:true,color:"0F172A",margin:0,fit:"shrink"});s.addText(item.body||"",{x:.72,y:item.layout==="title"?2.0:1.45,w:item.image?7.2:11.7,h:item.layout==="title"?2:4.8,fontFace:"Aptos",fontSize:item.layout==="title"?20:18,color:"334155",breakLine:false,margin:.03,fit:"shrink",valign:"top"});if(item.image){s.addImage({data:item.image,x:8.2,y:1.45,w:4.25,h:4.6});}if(item.notes&&typeof s.addNotes==="function")s.addNotes(item.notes);}const blob=await pptx.write({outputType:"blob"});const pptxBytes=new Uint8Array(await blob.arrayBuffer());const {default:JSZip}=await import("jszip");const zip=await JSZip.loadAsync(pptxBytes);const slideFiles=Object.keys(zip.files).filter((name)=>/^ppt\/slides\/slide\d+\.xml$/.test(name));if(!zip.file("[Content_Types].xml")||!zip.file("ppt/presentation.xml")||slideFiles.length!==slides.length)throw new Error("PPTX validation failed before download.");downloadBytes(pptxBytes,`${title||"presentation"}.pptx`,"application/vnd.openxmlformats-officedocument.presentationml.presentation");setMessage(`Validated PPTX generated with ${slideFiles.length} slide${slideFiles.length===1?"":"s"}.`);}catch(err){setError(err?.message||"PPTX export failed.");}}
 async function exportPdf(){setError("");try{const{PDFDocument,StandardFonts,rgb}=await import("pdf-lib");const doc=await PDFDocument.create();const normal=await doc.embedFont(StandardFonts.Helvetica),bold=await doc.embedFont(StandardFonts.HelveticaBold);for(const item of slides){const page=doc.addPage([960,540]);const bg=item.background.replace("#","");const r=parseInt(bg.slice(0,2),16)/255,g=parseInt(bg.slice(2,4),16)/255,b=parseInt(bg.slice(4,6),16)/255;page.drawRectangle({x:0,y:0,width:960,height:540,color:rgb(r,g,b)});page.drawText(item.title||"",{x:50,y:460,size:28,font:bold,color:rgb(.06,.09,.16),maxWidth:860});const lines=String(item.body||"").split(/\n/).slice(0,12);lines.forEach((line,i)=>page.drawText(line,{x:56,y:400-i*28,size:17,font:normal,color:rgb(.2,.27,.36),maxWidth:item.image?520:840}));if(item.image){try{const raw=Uint8Array.from(atob(item.image.split(",")[1]),c=>c.charCodeAt(0));const img=item.image.startsWith("data:image/png")?await doc.embedPng(raw):await doc.embedJpg(raw);page.drawImage(img,{x:620,y:120,width:280,height:260});}catch{}}}const bytes=await doc.save({useObjectStreams:true});const verified=await PDFDocument.load(bytes);if(verified.getPageCount()!==slides.length)throw new Error("PDF validation failed: slide/page count changed during export.");downloadBytes(bytes,`${title||"presentation"}.pdf`,"application/pdf");setMessage(`Validated ${verified.getPageCount()}-page PDF slide handout generated. PPTX remains the highest-fidelity export.`);}catch(err){setError(err?.message||"PDF export failed.");}}
 async function exportPng(){try{const canvas=document.createElement("canvas");canvas.width=1280;canvas.height=720;const ctx=canvas.getContext("2d");ctx.fillStyle=slide.background;ctx.fillRect(0,0,1280,720);ctx.fillStyle="#0f172a";ctx.font="700 48px system-ui";ctx.fillText(slide.title||"",70,100,1100);ctx.font="28px system-ui";ctx.fillStyle="#334155";String(slide.body||"").split(/\n/).slice(0,10).forEach((line,i)=>ctx.fillText(line,80,180+i*42,slide.image?700:1100));if(slide.image){const img=new Image();await new Promise((res,rej)=>{img.onload=res;img.onerror=rej;img.src=slide.image});ctx.drawImage(img,850,220,330,330);}const blob=await new Promise((resolve)=>canvas.toBlob(resolve,"image/png"));if(!blob||blob.size<100)throw new Error("PNG export validation failed.");downloadBytes(new Uint8Array(await blob.arrayBuffer()),`slide-${active+1}.png`,`image/png`);}catch(err){setError(err?.message||"Slide image export failed.");}}
 return <div className="space-y-4">
  <div className="flex flex-wrap items-center gap-2 rounded-2xl border border-navy-100 bg-white p-3 dark:border-navy-800 dark:bg-navy-900"><input className="mz-input max-w-md font-bold" value={title} onChange={(e)=>setTitle(e.target.value)} aria-label="Presentation title"/><span className="text-xs text-navy-400">{saveState}</span><div className="ml-auto flex flex-wrap gap-2"><select className="mz-input max-w-52 py-2" defaultValue="" onChange={(e)=>{if(e.target.value)template(e.target.value);e.target.value=""}}><option value="">Apply template…</option><option value="university">University Presentation</option><option value="research">Research Presentation</option><option value="business">Business Presentation</option><option value="project">Project Presentation</option></select><button className="mz-btn-secondary" onClick={()=>setPresenting(true)}><MonitorPlay className="h-4 w-4"/> Present</button><button className="mz-btn-secondary" onClick={exportPdf}><Download className="h-4 w-4"/> PDF</button><button className="mz-btn-primary" onClick={exportPptx}><Save className="h-4 w-4"/> PPTX</button></div></div>
  <div className="grid gap-4 lg:grid-cols-[190px_minmax(0,1fr)_300px]">
   <aside className="rounded-2xl border border-navy-100 bg-white p-2 dark:border-navy-800 dark:bg-navy-900"><div className="mb-2 flex gap-1"><button className="mz-btn-secondary flex-1 px-2" onClick={()=>add("title-content")}><Plus className="h-4 w-4"/> Slide</button><button className="mz-btn-ghost" onClick={duplicate} aria-label="Duplicate slide"><Copy className="h-4 w-4"/></button><button className="mz-btn-ghost" onClick={remove} aria-label="Delete slide"><Trash2 className="h-4 w-4"/></button></div><div className="max-h-[650px] space-y-2 overflow-auto">{slides.map((item,index)=><button key={item.id} onClick={()=>setActive(index)} className={`w-full rounded-xl border p-2 text-left ${active===index?"border-brand-500 bg-brand-50 dark:bg-brand-950/30":"border-navy-100 dark:border-navy-800"}`}><SlideCanvas slide={item} compact/><span className="mt-1 block text-center text-[11px] font-semibold">Slide {index+1}</span></button>)}</div></aside>
   <main className="rounded-2xl border border-navy-100 bg-slate-200 p-4 dark:border-navy-800 dark:bg-navy-950"><div className="mb-3 flex flex-wrap gap-2"><button className="mz-btn-secondary" disabled={active===0} onClick={()=>move(-1)}>Move left</button><button className="mz-btn-secondary" disabled={active===slides.length-1} onClick={()=>move(1)}>Move right</button><button className="mz-btn-secondary" onClick={exportPng}>Export slide PNG</button></div><SlideCanvas slide={slide}/></main>
   <aside className="space-y-3"><section className="mz-card p-4"><h3 className="font-bold">Slide content</h3><label className="mt-3 block text-xs font-semibold">Layout<select className="mz-input mt-1" value={slide.layout} onChange={(e)=>update({layout:e.target.value})}><option value="title">Title slide</option><option value="title-content">Title + content</option><option value="two-column">Two-column</option><option value="image">Image slide</option><option value="blank">Blank</option></select></label><label className="mt-3 block text-xs font-semibold">Title<input className="mz-input mt-1" value={slide.title} onChange={(e)=>update({title:e.target.value})}/></label><label className="mt-3 block text-xs font-semibold">Content<textarea className="mz-input mt-1 min-h-32" value={slide.body} onChange={(e)=>update({body:e.target.value})}/></label></section><section className="mz-card p-4"><h3 className="font-bold">Visuals</h3><label className="mt-3 block text-xs font-semibold">Background<input className="ml-2 h-9 w-12 align-middle" type="color" value={slide.background} onChange={(e)=>update({background:e.target.value})}/></label><button className="mz-btn-secondary mt-3 w-full" onClick={()=>imageRef.current?.click()}><ImageIcon className="h-4 w-4"/> Add image</button><input ref={imageRef} hidden type="file" accept="image/png,image/jpeg,image/webp" onChange={(e)=>imageFile(e.target.files?.[0])}/>{slide.image?<button className="mz-btn-ghost mt-2 w-full" onClick={()=>update({image:""})}>Remove image</button>:null}</section><section className="mz-card p-4"><h3 className="font-bold">Speaker notes</h3><textarea className="mz-input mt-3 min-h-28" value={slide.notes} onChange={(e)=>update({notes:e.target.value})} placeholder="Notes for this slide"/></section></aside>
  </div>
  {message?<div className="rounded-2xl border border-emerald-200 bg-emerald-50 p-3 text-sm text-emerald-800 dark:border-emerald-900/50 dark:bg-emerald-950/30 dark:text-emerald-200">{message}</div>:null}{error?<div role="alert" className="rounded-2xl border border-red-200 bg-red-50 p-3 text-sm text-red-800 dark:border-red-900/50 dark:bg-red-950/30 dark:text-red-200">{error}</div>:null}
  {presenting?<div className="fixed inset-0 z-[120] flex flex-col bg-black p-4"><div className="mb-3 flex justify-end gap-2"><button className="mz-btn-secondary" disabled={active===0} onClick={()=>setActive((i)=>Math.max(0,i-1))}>Previous</button><button className="mz-btn-secondary" disabled={active===slides.length-1} onClick={()=>setActive((i)=>Math.min(slides.length-1,i+1))}>Next</button><button className="mz-btn-primary" onClick={()=>setPresenting(false)}>Exit</button></div><div className="m-auto w-full max-w-6xl"><SlideCanvas slide={slide}/></div></div>:null}
 </div>;
}
