import { useEffect, useMemo, useRef, useState } from "react";
import { BarChart3, Bold, Download, FilePlus2, Italic, Plus, Printer, Save, Search, Sheet, Trash2, Upload } from "lucide-react";
import { downloadBytes } from "../../lib/download";
import { colName, cellKey, parseRef, rangeKeys, computeCell, formatValue } from "../../lib/spreadsheet/formulas";

const ROWS = 40;
const COLS = 16;
const STORAGE_KEY = "mz-online-excel-workbook-v1";
const MAX_IMPORT_BYTES = 15 * 1024 * 1024;
const uid = () => (globalThis.crypto?.randomUUID?.() || `${Date.now()}-${Math.random()}`);

function emptySheet(name="Sheet 1") { return { id:uid(), name, cells:{}, formats:{} }; }
function readWorkbook() { try { const data=JSON.parse(localStorage.getItem(STORAGE_KEY)||"null"); if(data?.sheets?.length)return data; } catch{} return { title:"Untitled Spreadsheet", sheets:[emptySheet()], active:0 }; }

function parseChartRange(sheet,range){const keys=rangeKeys(range);const rows=[];for(const key of keys){const ref=parseRef(key);const val=computeCell(sheet,key);rows.push({key,row:ref.row,col:ref.col,val});}const grouped=new Map();rows.forEach((item)=>{if(!grouped.has(item.row))grouped.set(item.row,[]);grouped.get(item.row).push(item)});return [...grouped.values()].map((items,index)=>({label:String(items[0]?.val||`Row ${index+1}`),value:Number(items.find((x)=>x.col!==items[0].col)?.val??items[0]?.val)})).filter((x)=>Number.isFinite(x.value)).slice(0,20);}

function ChartPreview({data,type}){if(!data.length)return <div className="flex h-52 items-center justify-center text-sm text-navy-400">No numeric chart data.</div>;const max=Math.max(...data.map(d=>Math.abs(d.value)),1);if(type==="pie"){const total=data.reduce((a,b)=>a+Math.max(0,b.value),0)||1;let angle=-Math.PI/2;const paths=data.map((d,i)=>{const share=Math.max(0,d.value)/total;const next=angle+share*Math.PI*2;const x1=100+80*Math.cos(angle),y1=100+80*Math.sin(angle),x2=100+80*Math.cos(next),y2=100+80*Math.sin(next);const large=share>.5?1:0;const path=`M100 100 L${x1} ${y1} A80 80 0 ${large} 1 ${x2} ${y2} Z`;angle=next;return <path key={i} d={path} fill={`hsl(${(i*67)%360} 70% 58%)`}/>});return <svg viewBox="0 0 200 200" className="mx-auto h-52 w-52">{paths}</svg>}
 const points=data.map((d,i)=>[20+(i*(360/Math.max(1,data.length-1))),180-(Math.max(0,d.value)/max)*150]);if(type==="line"||type==="area")return <svg viewBox="0 0 400 210" className="h-52 w-full">{type==="area"?<polygon points={`20,180 ${points.map(p=>p.join(",")).join(" ")} ${points.at(-1)[0]},180`} fill="rgba(37,99,235,.16)"/>:null}<polyline points={points.map(p=>p.join(",")).join(" ")} fill="none" stroke="currentColor" strokeWidth="4" className="text-brand-600"/>{points.map((p,i)=><circle key={i} cx={p[0]} cy={p[1]} r="4" fill="currentColor" className="text-brand-600"/>)}</svg>;
 return <div className="flex h-52 items-end gap-2 border-b border-navy-200 px-2 dark:border-navy-700">{data.map((d,i)=><div key={i} className="flex min-w-0 flex-1 flex-col items-center"><div title={`${d.label}: ${d.value}`} className="w-full rounded-t bg-brand-500" style={{height:`${Math.max(4,Math.abs(d.value)/max*170)}px`}}/><span className="mt-1 w-full truncate text-center text-[10px] text-navy-400">{d.label}</span></div>)}</div>;
}

export default function OnlineExcel(){
 const initial=useMemo(readWorkbook,[]);const [title,setTitle]=useState(initial.title||"Untitled Spreadsheet");const [sheets,setSheets]=useState(initial.sheets);const [active,setActive]=useState(Math.min(initial.active||0,initial.sheets.length-1));const [selected,setSelected]=useState("A1");const [formula,setFormula]=useState(initial.sheets[active]?.cells?.A1||"");const [saveState,setSaveState]=useState("Saved");const [error,setError]=useState("");const [message,setMessage]=useState("");const [chart,setChart]=useState({open:false,type:"bar",range:"A1:B6"});const [search,setSearch]=useState("");const [zoom,setZoom]=useState(100);const fileRef=useRef(null);const sheet=sheets[active];
 useEffect(()=>{setFormula(sheet?.cells?.[selected]??"")},[selected,active]);
 useEffect(()=>{setSaveState("Saving…");const timer=setTimeout(()=>{try{localStorage.setItem(STORAGE_KEY,JSON.stringify({title,sheets,active,savedAt:Date.now()}));setSaveState("Saved")}catch{setSaveState("Local save unavailable")}},450);return()=>clearTimeout(timer)},[title,sheets,active]);
 const updateSheet=(updater)=>setSheets((all)=>all.map((item,index)=>index===active?updater(item):item));
 const commit=(value=formula)=>{updateSheet((current)=>({...current,cells:{...current.cells,[selected]:value}}));setFormula(value);};
 const applyFormat=(patch)=>updateSheet((current)=>({...current,formats:{...current.formats,[selected]:{...(current.formats[selected]||{}),...patch}}}));
 function addSheet(){const next=emptySheet(`Sheet ${sheets.length+1}`);setSheets((all)=>[...all,next]);setActive(sheets.length);setSelected("A1");}
 function removeSheet(){if(sheets.length===1){setError("A workbook must contain at least one sheet.");return;}setSheets((all)=>all.filter((_,i)=>i!==active));setActive(Math.max(0,active-1));setSelected("A1");}
 async function importFile(file){if(!file)return;setError("");setMessage("");try{if(file.size>MAX_IMPORT_BYTES)throw new Error("Spreadsheet exceeds the 15 MB browser import safety limit.");const XLSX=await import("xlsx");const buffer=await file.arrayBuffer();const wb=XLSX.read(buffer,{type:"array",cellFormula:true,cellDates:true});const next=wb.SheetNames.map((name)=>{const ws=wb.Sheets[name];const range=XLSX.utils.decode_range(ws["!ref"]||"A1:A1");const cells={};for(let r=range.s.r;r<=range.e.r;r++)for(let c=range.s.c;c<=range.e.c;c++){const addr=XLSX.utils.encode_cell({r,c}),cell=ws[addr];if(cell){cells[addr]=cell.f?`=${cell.f}`:cell.v instanceof Date?cell.v.toISOString().slice(0,10):String(cell.v??"");}}return {id:uid(),name,cells,formats:{}}});if(!next.length)throw new Error("The workbook does not contain readable sheets.");setSheets(next);setActive(0);setSelected("A1");setTitle(file.name.replace(/\.(xlsx|xls|csv)$/i,""));setMessage(`Imported ${next.length} sheet${next.length===1?"":"s"}.`);}catch(err){setError(err?.message||"The spreadsheet could not be imported.");}}
 async function exportXlsx(){setError("");try{const XLSX=await import("xlsx");const wb=XLSX.utils.book_new();for(const item of sheets){const maxRow=Math.max(0,...Object.keys(item.cells).map(k=>parseRef(k)?.row||0)),maxCol=Math.max(0,...Object.keys(item.cells).map(k=>parseRef(k)?.col||0));const aoa=Array.from({length:maxRow+1},()=>Array(maxCol+1).fill(""));for(const [key,value] of Object.entries(item.cells)){const ref=parseRef(key);if(ref)aoa[ref.row][ref.col]=String(value).startsWith("=")?computeCell(item,key):value;}const ws=XLSX.utils.aoa_to_sheet(aoa);for(const [key,value] of Object.entries(item.cells))if(String(value).startsWith("=")&&ws[key]){ws[key].f=String(value).slice(1);delete ws[key].v;}XLSX.utils.book_append_sheet(wb,ws,item.name.slice(0,31)||"Sheet");}const out=XLSX.write(wb,{bookType:"xlsx",type:"array"});const verified=XLSX.read(out,{type:"array",cellFormula:true});if(verified.SheetNames.length!==sheets.length)throw new Error("XLSX validation failed: sheet count changed during export.");downloadBytes(new Uint8Array(out),`${title||"spreadsheet"}.xlsx`,"application/vnd.openxmlformats-officedocument.spreadsheetml.sheet");setMessage(`Validated XLSX generated with ${verified.SheetNames.length} sheet${verified.SheetNames.length===1?"":"s"}.`);}catch(err){setError(err?.message||"XLSX export failed.");}}
 async function exportCsv(){try{const XLSX=await import("xlsx");const maxRow=Math.max(0,...Object.keys(sheet.cells).map(k=>parseRef(k)?.row||0)),maxCol=Math.max(0,...Object.keys(sheet.cells).map(k=>parseRef(k)?.col||0));const aoa=Array.from({length:maxRow+1},()=>Array(maxCol+1).fill(""));for(const key of Object.keys(sheet.cells)){const ref=parseRef(key);aoa[ref.row][ref.col]=computeCell(sheet,key);}const csv=XLSX.utils.sheet_to_csv(XLSX.utils.aoa_to_sheet(aoa));downloadBytes(new TextEncoder().encode(csv),`${sheet.name}.csv`,"text/csv;charset=utf-8");}catch(err){setError(err?.message||"CSV export failed.");}}
 function findCell(){const query=search.trim().toLowerCase();if(!query){setMessage("Enter a value or text to search this sheet.");return;}const ordered=[];for(let r=0;r<ROWS;r++)for(let c=0;c<COLS;c++)ordered.push(cellKey(r,c));const start=Math.max(-1,ordered.indexOf(selected));for(let offset=1;offset<=ordered.length;offset++){const key=ordered[(start+offset)%ordered.length];const raw=String(sheet.cells[key]??"");const shown=String(computeCell(sheet,key)??"");if(raw.toLowerCase().includes(query)||shown.toLowerCase().includes(query)){setSelected(key);setFormula(raw);setMessage(`Found “${search}” in ${key}.`);return;}}setMessage(`No match for “${search}” on ${sheet.name}.`);}
 const chartData=useMemo(()=>parseChartRange(sheet,chart.range),[sheet,chart.range]);
 const selectedFormat=sheet.formats[selected]||{};
 return <div className="space-y-4">
  <div className="flex flex-wrap items-center gap-2 rounded-2xl border border-navy-100 bg-white p-3 dark:border-navy-800 dark:bg-navy-900"><input className="mz-input max-w-sm font-bold" value={title} onChange={(e)=>setTitle(e.target.value)} aria-label="Workbook title"/><span className="text-xs text-navy-400">{saveState}</span><div className="ml-auto flex flex-wrap gap-2"><button className="mz-btn-secondary" onClick={()=>fileRef.current?.click()}><Upload className="h-4 w-4"/> Import XLSX/CSV</button><input ref={fileRef} hidden type="file" accept=".xlsx,.xls,.csv,text/csv,application/vnd.openxmlformats-officedocument.spreadsheetml.sheet" onChange={(e)=>importFile(e.target.files?.[0])}/><button className="mz-btn-secondary" onClick={()=>window.print()}><Printer className="h-4 w-4"/> Print</button><button className="mz-btn-secondary" onClick={exportCsv}><Download className="h-4 w-4"/> CSV</button><button className="mz-btn-primary" onClick={exportXlsx}><Save className="h-4 w-4"/> XLSX</button></div></div>
  <div className="flex flex-wrap items-center gap-2 rounded-2xl border border-navy-100 bg-white p-2 dark:border-navy-800 dark:bg-navy-900"><div className="relative min-w-[220px] flex-1 sm:max-w-sm"><Search className="pointer-events-none absolute left-3 top-1/2 h-4 w-4 -translate-y-1/2 text-navy-400"/><input className="mz-input pl-9" value={search} onChange={(e)=>setSearch(e.target.value)} onKeyDown={(e)=>{if(e.key==="Enter")findCell();}} placeholder="Search this sheet" aria-label="Search spreadsheet"/></div><button className="mz-btn-secondary" onClick={findCell}>Find next</button><label className="ml-auto flex items-center gap-2 text-xs font-semibold">Zoom<select className="mz-input w-24 py-2" value={zoom} onChange={(e)=>setZoom(Number(e.target.value))}><option value="75">75%</option><option value="100">100%</option><option value="125">125%</option><option value="150">150%</option></select></label></div>
  <div className="flex flex-wrap items-center gap-2 rounded-2xl border border-navy-100 bg-white p-2 dark:border-navy-800 dark:bg-navy-900"><button className={`mz-btn-ghost ${selectedFormat.bold?"bg-brand-50 text-brand-700":""}`} onClick={()=>applyFormat({bold:!selectedFormat.bold})} aria-label="Bold"><Bold className="h-4 w-4"/></button><button className={`mz-btn-ghost ${selectedFormat.italic?"bg-brand-50 text-brand-700":""}`} onClick={()=>applyFormat({italic:!selectedFormat.italic})} aria-label="Italic"><Italic className="h-4 w-4"/></button><label className="text-xs font-semibold">Text <input type="color" className="ml-1 h-8 w-10 align-middle" value={selectedFormat.color||"#0f172a"} onChange={(e)=>applyFormat({color:e.target.value})}/></label><label className="text-xs font-semibold">Fill <input type="color" className="ml-1 h-8 w-10 align-middle" value={selectedFormat.fill||"#ffffff"} onChange={(e)=>applyFormat({fill:e.target.value})}/></label><select className="mz-input max-w-40 py-2" value={selectedFormat.align||"left"} onChange={(e)=>applyFormat({align:e.target.value})}><option value="left">Align left</option><option value="center">Align center</option><option value="right">Align right</option></select><select className="mz-input max-w-40 py-2" value={selectedFormat.number||"general"} onChange={(e)=>applyFormat({number:e.target.value})}><option value="general">General</option><option value="currency">Currency</option><option value="percentage">Percentage</option><option value="date">Date</option></select><button className="mz-btn-secondary ml-auto" onClick={()=>setChart((c)=>({...c,open:!c.open}))}><BarChart3 className="h-4 w-4"/> Chart</button></div>
  <div className="grid grid-cols-[90px_minmax(0,1fr)] gap-2"><div className="rounded-xl border border-navy-200 bg-navy-50 px-3 py-2 text-center font-mono text-sm font-bold dark:border-navy-700 dark:bg-navy-900">{selected}</div><input className="mz-input font-mono" value={formula} onChange={(e)=>setFormula(e.target.value)} onBlur={()=>commit()} onKeyDown={(e)=>{if(e.key==="Enter"){commit();e.currentTarget.blur();}}} aria-label="Formula bar" placeholder="Value or formula, e.g. =SUM(A1:A5)"/></div>
  {chart.open?<section className="mz-card grid gap-4 p-4 md:grid-cols-[250px_1fr]"><div><h3 className="font-bold">Chart preview</h3><label className="mt-3 block text-xs font-semibold">Range<input className="mz-input mt-1" value={chart.range} onChange={(e)=>setChart(c=>({...c,range:e.target.value.toUpperCase()}))} placeholder="A1:B6"/></label><label className="mt-3 block text-xs font-semibold">Type<select className="mz-input mt-1" value={chart.type} onChange={(e)=>setChart(c=>({...c,type:e.target.value}))}><option value="bar">Bar</option><option value="line">Line</option><option value="area">Area</option><option value="pie">Pie</option></select></label><p className="mt-3 text-xs leading-5 text-navy-500">Use a two-column range: first column labels, second column numeric values. The chart is a browser preview; XLSX export currently preserves sheet data/formulas, not chart objects.</p></div><ChartPreview data={chartData} type={chart.type}/></section>:null}
  <section className="overflow-auto rounded-2xl border border-navy-200 bg-white shadow-sm dark:border-navy-700 dark:bg-navy-900"><div className="min-w-[1050px] origin-top-left" style={{zoom:`${zoom}%`}}><div className="sticky top-0 z-20 grid" style={{gridTemplateColumns:`52px repeat(${COLS}, 110px)`}}><div className="sticky left-0 z-30 border-b border-r border-navy-200 bg-navy-100 dark:border-navy-700 dark:bg-navy-800"/>{Array.from({length:COLS},(_,c)=><div key={c} className="border-b border-r border-navy-200 bg-navy-100 px-2 py-2 text-center text-xs font-bold dark:border-navy-700 dark:bg-navy-800">{colName(c)}</div>)}</div>{Array.from({length:ROWS},(_,r)=><div key={r} className="grid" style={{gridTemplateColumns:`52px repeat(${COLS}, 110px)`}}><div className="sticky left-0 z-10 border-b border-r border-navy-200 bg-navy-50 px-2 py-2 text-center text-xs font-semibold dark:border-navy-700 dark:bg-navy-900">{r+1}</div>{Array.from({length:COLS},(_,c)=>{const key=cellKey(r,c),raw=sheet.cells[key]??"",fmt=sheet.formats[key]||{},display=formatValue(computeCell(sheet,key),fmt);return <input key={key} aria-label={`Cell ${key}`} value={key===selected?raw:display} onFocus={()=>{setSelected(key);setFormula(raw)}} onChange={(e)=>{setSelected(key);setFormula(e.target.value);updateSheet(cur=>({...cur,cells:{...cur.cells,[key]:e.target.value}}))}} className={`min-w-0 border-b border-r border-navy-100 px-2 py-2 text-sm outline-none focus:z-10 focus:ring-2 focus:ring-brand-500 dark:border-navy-800 dark:bg-navy-900 ${key===selected?"ring-2 ring-brand-500":""}`} style={{fontWeight:fmt.bold?700:400,fontStyle:fmt.italic?"italic":"normal",color:fmt.color||undefined,backgroundColor:fmt.fill||undefined,textAlign:fmt.align||"left"}}/>})}</div>)}</div></section>
  <div className="flex flex-wrap items-center gap-2 rounded-2xl border border-navy-100 bg-white p-2 dark:border-navy-800 dark:bg-navy-900"><Sheet className="ml-2 h-4 w-4 text-brand-600"/>{sheets.map((item,index)=><button key={item.id} className={index===active?"mz-btn-primary":"mz-btn-ghost"} onClick={()=>{setActive(index);setSelected("A1")}}>{item.name}</button>)}<button className="mz-btn-secondary" onClick={addSheet}><Plus className="h-4 w-4"/> Sheet</button><button className="mz-btn-ghost" onClick={removeSheet}><Trash2 className="h-4 w-4"/> Remove</button><span className="ml-auto max-w-3xl text-right text-xs text-navy-400">Formulas: SUM, AVERAGE, MIN, MAX, COUNT, COUNTA, IF, AND, OR, ROUND, ROUNDUP, ROUNDDOWN, ABS, MOD, CONCAT, LEFT, RIGHT, MID, LEN, TODAY, NOW + A1 arithmetic</span></div>
  {message?<div className="rounded-2xl border border-emerald-200 bg-emerald-50 p-3 text-sm text-emerald-800 dark:border-emerald-900/50 dark:bg-emerald-950/30 dark:text-emerald-200">{message}</div>:null}{error?<div role="alert" className="rounded-2xl border border-red-200 bg-red-50 p-3 text-sm text-red-800 dark:border-red-900/50 dark:bg-red-950/30 dark:text-red-200">{error}</div>:null}
 </div>;
}
