import { writeFileSync } from "node:fs";
import { fileURLToPath } from "node:url";
import { dirname, resolve } from "node:path";
import { tools } from "../src/data/tools.js";
import { categories } from "../src/data/categories.js";
import { universityPolicies } from "../src/data/universities/policies.js";
import { getSearchFocusedTools } from "./seo-index-plan.js";
const __dirname=dirname(fileURLToPath(import.meta.url));
const BASE_URL=String(process.env.SITE_URL||process.env.VITE_SITE_URL||"https://mztoolshouse.com").replace(/\/+$/g,"");
const today=new Date().toISOString().slice(0,10);
const staticRoutes=[["/",1,"daily"],["/tools",.95,"daily"],["/categories",.8,"weekly"],["/office",.9,"weekly"],["/student-hub",.9,"weekly"],["/about",.5,"monthly"],["/contact",.4,"monthly"],["/privacy-policy",.3,"yearly"],["/terms",.3,"yearly"],["/disclaimer",.3,"yearly"]];
const categoryRoutes=categories.filter(c=>c.seoIndexable!==false).map(c=>[c.route||`/categories/${c.slug}`,.72,"weekly"]);
const focused=getSearchFocusedTools(tools);
const toolRoutes=focused.map(t=>[t.route||`/tools/${t.id}`,.88,"weekly"]);
const universityRoutes=universityPolicies.filter(u=>u.verified===true).map(u=>[`/gpa-calculator/${u.id}`,.76,"monthly"]);
const seen=new Set();const routes=[...staticRoutes,...categoryRoutes,...toolRoutes,...universityRoutes].filter(([p])=>!seen.has(p)&&seen.add(p));
const esc=s=>String(s).replace(/&/g,"&amp;").replace(/</g,"&lt;").replace(/>/g,"&gt;");
const entries=routes.map(([p,pr,f])=>`  <url>\n    <loc>${esc(BASE_URL+p)}</loc>\n    <lastmod>${today}</lastmod>\n    <changefreq>${f}</changefreq>\n    <priority>${Number(pr).toFixed(2)}</priority>\n  </url>`).join("\n");
const xml=`<?xml version="1.0" encoding="UTF-8"?>\n<?xml-stylesheet type="text/xsl" href="/sitemap.xsl"?>\n<urlset xmlns="http://www.sitemaps.org/schemas/sitemap/0.9">\n${entries}\n</urlset>\n`;
const robots=`User-agent: *\nAllow: /\nDisallow: /.netlify/\nDisallow: /tool-health\nDisallow: /settings\n\nSitemap: ${BASE_URL}/sitemap.xml\n`;
writeFileSync(resolve(__dirname,"../public/sitemap.xml"),xml,"utf8");writeFileSync(resolve(__dirname,"../public/robots.txt"),robots,"utf8");
try{writeFileSync(resolve(__dirname,"../dist/sitemap.xml"),xml,"utf8");writeFileSync(resolve(__dirname,"../dist/robots.txt"),robots,"utf8")}catch{}
console.log(`Search-focused sitemap: ${routes.length} URLs (${focused.length} enriched tools)`);
