import {
  Calculator, Percent, CalendarCheck, Cake, Tag, Sigma, Divide, Clock,
  FilePlus, Scissors, FileDown, Image, RotateCw, FileX, FileOutput,
  ListOrdered, Hash, Stamp, Info, ImageDown, Scaling, Crop, IdCard,
  Type, CaseSensitive, Eraser, Layers, Sparkles, ArrowDownAZ,
  FlipHorizontal, Link, BookOpen, Braces, CheckCircle, Minimize2, Lock,
  Unlock, Code, Regex, Binary, Fingerprint, Key, FileSignature, UserRound,
  Mail, FileText, Calendar, Trophy, Timer, Hourglass, ListChecks,
  CalendarDays, Shuffle, GraduationCap, ScanLine, HelpCircle, BriefcaseBusiness,
  HeartPulse, Salad, FilePenLine, Table2, Presentation, BookOpenCheck, FileSearch, Globe2,
} from "lucide-react";

const ICONS = {
  calculator: Calculator,
  percent: Percent,
  "calendar-check": CalendarCheck,
  cake: Cake,
  tag: Tag,
  sigma: Sigma,
  divide: Divide,
  clock: Clock,
  "file-plus": FilePlus,
  scissors: Scissors,
  "file-down": FileDown,
  image: Image,
  "rotate-cw": RotateCw,
  "file-x": FileX,
  "file-output": FileOutput,
  "list-ordered": ListOrdered,
  hash: Hash,
  stamp: Stamp,
  info: Info,
  "image-down": ImageDown,
  scaling: Scaling,
  crop: Crop,
  "id-card": IdCard,
  type: Type,
  "case-sensitive": CaseSensitive,
  eraser: Eraser,
  layers: Layers,
  sparkles: Sparkles,
  "arrow-down-a-z": ArrowDownAZ,
  "flip-horizontal": FlipHorizontal,
  link: Link,
  "book-open": BookOpen,
  braces: Braces,
  "check-circle": CheckCircle,
  "minimize-2": Minimize2,
  lock: Lock,
  unlock: Unlock,
  code: Code,
  regex: Regex,
  binary: Binary,
  fingerprint: Fingerprint,
  key: Key,
  "file-signature": FileSignature,
  "file-user": UserRound,
  mail: Mail,
  "file-text": FileText,
  calendar: Calendar,
  trophy: Trophy,
  timer: Timer,
  hourglass: Hourglass,
  "list-checks": ListChecks,
  "calendar-days": CalendarDays,
  shuffle: Shuffle,
  "graduation-cap": GraduationCap,
  "scan-line": ScanLine,
  "help-circle": HelpCircle,
  "briefcase-business": BriefcaseBusiness,
  "heart-pulse": HeartPulse,
  salad: Salad,
  "file-pen-line": FilePenLine,
  "table-2": Table2,
  presentation: Presentation,
  "book-open-check": BookOpenCheck,
  "file-search": FileSearch,
  "globe-2": Globe2,
};

/**
 * Resolves an icon-name string from the tool/category registries into a
 * lucide-react component. Falls back to HelpCircle if the name is unknown,
 * so a typo in the registry never crashes the page.
 */
export default function ToolIcon({ name, className = "h-5 w-5", ...props }) {
  const Icon = ICONS[name] || HelpCircle;
  return <Icon className={className} aria-hidden="true" {...props} />;
}
